from pathlib import Path
import re
p=Path("app/src/main/java/com/saomi/telsiz/ui/AppRoot.kt")
s=p.read_text()
s=s.replace("import com.saomi.telsiz.data.LocalStore","import com.saomi.telsiz.data.LocalStore\\nimport com.saomi.telsiz.data.MemberStatusApi\\nimport com.saomi.telsiz.data.MemberStatus")
s=s.replace("val backend = remember { BackendApi(context) }","val backend = remember { BackendApi(context) }\\n    val memberApi = remember { MemberStatusApi() }\\n    var members by remember { mutableStateOf<List<MemberStatus>>(emptyList()) }\\n    var showMembers by remember { mutableStateOf(false) }")
s=s.replace("    val picker = rememberLauncherForActivityResult","    LaunchedEffect(session?.userId) {\\n        val current = session ?: return@LaunchedEffect\\n        while (true) { memberApi.heartbeat(current); members = memberApi.members(current); delay(30000) }\\n    }\\n\\n    val picker = rememberLauncherForActivityResult")
s=s.replace("    Scaffold(","    if (showMembers) { AlertDialog(onDismissRequest={showMembers=false}, title={Text(\\\"MELEHAT ÜYELERİ • $${members.size}\\\")}, text={ Column { members.forEach { m -> Row(verticalAlignment=Alignment.CenterVertically) { Text(\\\"●\\\",color=if(m.online) Color(0xFF34C759) else Color.Gray); Spacer(Modifier.width(8.dp)); Text(m.name); Spacer(Modifier.weight(1f)); Text(if(m.online) \\\"Aktif\\\" else \\\"Çevrimdışı\\\") } } } }, confirmButton={TextButton(onClick={showMembers=false}){Text(\\\"KAPAT\\\")}}) }\\n\\n    Scaffold(",1)
s=s.replace("if (radioOn && !transmitting) {\\n                    Canvas","if (false) {\\n                    Canvas")
s=s.replace("MELEHAT TELSİZ C54","MELEHAT TELSİZ C55").replace("C54 •","C55 •")
p.write_text(s)
m=Path("app/src/main/java/com/saomi/telsiz/data/MemberStatusApi.kt")
m.write_text("""package com.saomi.telsiz.data\nimport com.saomi.telsiz.BuildConfig\nimport com.saomi.telsiz.auth.AuthSession\nimport kotlinx.coroutines.Dispatchers\nimport kotlinx.coroutines.withContext\nimport okhttp3.MediaType.Companion.toMediaType\nimport okhttp3.OkHttpClient\nimport okhttp3.Request\nimport okhttp3.RequestBody.Companion.toRequestBody\nimport org.json.JSONArray\ndata class MemberStatus(val id:String,val name:String,val avatarUrl:String?,val online:Boolean)\nclass MemberStatusApi { private val http=OkHttpClient(); private val json=\\\"application/json\\\".toMediaType(); private fun req(s:AuthSession,r:String)=Request.Builder().url(BuildConfig.SUPABASE_URL.trimEnd(\\\"/\\\")+\\\"/rest/v1/rpc/\\\"+r).addHeader(\\\"apikey\\\",BuildConfig.SUPABASE_PUBLISHABLE_KEY).addHeader(\\\"Authorization\\\",\\\"Bearer \\\"+s.accessToken).addHeader(\\\"Content-Type\\\",\\\"application/json\\\"); suspend fun heartbeat(s:AuthSession)=withContext(Dispatchers.IO){runCatching{http.newCall(req(s,\\\"melehat_heartbeat\\\").post(\\\"{}\\\".toRequestBody(json)).build()).execute().close()}}; suspend fun members(s:AuthSession):List<MemberStatus> = withContext(Dispatchers.IO){runCatching{http.newCall(req(s,\\\"get_melehat_members\\\").post(\\\"{}\\\".toRequestBody(json)).build()).execute().use{r->if(!r.isSuccessful)return@use emptyList();val a=JSONArray(r.body?.string().orEmpty());(0 until a.length()).map{i->a.getJSONObject(i).let{o->MemberStatus(o.optString(\\\"user_id\\\"),o.optString(\\\"display_name\\\"),o.optString(\\\"avatar_url\\\").takeIf{it.isNotBlank()},o.optBoolean(\\\"online\\\"))}}}}}.getOrDefault(emptyList())} }\n""")
b=Path("app/build.gradle.kts");t=b.read_text();t=re.sub(r"applicationId\\s*=\\s*\\\"[^\\\"]+\\\"","applicationId = \\\"com.melehat.telsiz.c55\\\"",t,1);t=re.sub(r"versionCode\\s*=\\s*\\d+","versionCode = 55",t,1);t=re.sub(r"versionName\\s*=\\s*\\\"[^\\\"]+\\\"","versionName = \\\"C55\\\"",t,1);b.write_text(t)